# Generated by Django 5.2.6 on 2025-09-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='original_photo',
            field=models.ImageField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='restored_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='photos',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Complete', 'complete')], default='pending'),
        ),
    ]
